# Generated by Django 5.1.7 on 2025-03-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='pet_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='owners.pettype'),
            preserve_default=False,
        ),
    ]
