# Generated by Django 5.1.7 on 2025-03-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('bird_type', models.CharField(choices=[('ابيض شركات', 'ابيض شركات'), ('ساسو', 'ساسو'), ('بلدي مشعر', 'بلدي مشعر'), ('هجين عالي', 'هجين عالي'), ('جيل تاني لحم', 'جيل تاني لحم'), ('رزي برابر', 'رزي برابر'), ('رزي ع وشه', 'رزي ع وشه'), ('رزي ديوك', 'رزي ديوك'), ('جميزه', 'جميزه'), ('بغالي', 'بغالي'), ('فرنساوي شريري', 'فرنساوي شريري'), ('بيور ستار', 'بيور ستار'), ('مسكوف', 'مسكوف'), ('سمان عمر', 'سمان عمر'), ('رومي اسمر', 'رومي اسمر'), ('رومي ابيض', 'رومي ابيض')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('payed_money', models.IntegerField()),
                ('date_of_payment', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
