# Generated by Django 5.1.7 on 2025-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birds', '0002_birddailyprice_bird_price_bird_remaining_to_pay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birddailyprice',
            name='bird_type',
            field=models.CharField(max_length=50),
        ),
    ]
