# Generated by Django 5.1.7 on 2025-03-16 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0002_alter_owner_pet_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.FloatField()),
                ('weight_in_kg', models.FloatField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('visit_date', models.DateField()),
                ('next_check_date', models.DateField()),
                ('by_user', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owner')),
                ('pet_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newvisit.pettype')),
            ],
        ),
    ]
